language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base libgtk2.0-dev
    - source /opt/qt58/bin/qt58-env.sh

script:
  - cd src/
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - make -j4
  - find . | grep des
  - mkdir -p appdir/usr/bin ; mkdir -p appdir/usr/share/applications ; cd appdir
  - cp ../src/updater ./usr/bin
  - cp ../resources/updater.desktop ./usr/share/applications/
  - touch updater.png # FIXME
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/updater -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/updater -appimage 
  - curl --upload-file ./Updater-*.AppImage https://transfer.sh/Updater-git$(git rev-parse --short HEAD)-x86_64.AppImage 
